
platform :ios, '10.0'
use_frameworks!

target 'Meemo' do
	pod 'MXParallaxHeader'
    pod 'Alamofire', '~> 4.4'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Mixpanel'
    pod 'Firebase/Messaging'


end

